# Generated by Django 4.2.11 on 2026-06-05 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('ecr_repository', models.CharField(help_text='ECR repository-name from EventBridge event', max_length=255, unique=True)),
                ('argo_app_name', models.CharField(help_text='Argo CD Application name', max_length=255)),
                ('argo_project', models.CharField(blank=True, default='', max_length=255)),
                ('repo_url', models.CharField(help_text='OCI repo URL, e.g. 197461532043.dkr.ecr.ap-northeast-1.amazonaws.com', max_length=512)),
                ('chart_path', models.CharField(help_text='Helm chart path, e.g. helm-main/exchange-activity', max_length=512)),
                ('enabled', models.BooleanField(default=True)),
                ('current_tag', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_tag', models.CharField(max_length=255)),
                ('image_digest', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('webhook', 'Webhook'), ('rollback', 'Rollback')], max_length=20)),
                ('argo_success', models.BooleanField(default=False)),
                ('argo_error', models.TextField(blank=True, default='')),
                ('raw_event', models.JSONField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='releases.releaseappconfig')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
